apiVersion: v1
kind: ConfigMap
metadata: 
  name: game-demo
data: 
  player_initial_lives: "3"
  ui_properties_file_name: user-interface.properties
  game.properties: |     #This file will be create in pod /confic dir  based on volumeMounts
    enemy.types=aliens,monsters
    player.maximum-lives=5
  user-interface.properties: |  #This file will be create in pod /confic dir based on volumeMounts
    color.good=purple
    color.bad=yellow
    allow.textmode=true  #if you change it and apply your value inner pod wont change in readOnly.true mode