apiVersion: batch/v1
kind: CronJob
metadata:
  name: helloworld-cron
spec:
#  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 3
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: busybox
            image: busybox
#            command: ["echo", "Something!!!"]
#            command:
#            - /bin/sh
#            - -c
#            -  date; echo hell
            command:
            - /bin/sh
            - -c
            -  tail -f /dev/null
          restartPolicy: Never