apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-autoscalar
spec:
  maxReplicas: 15
  minReplicas: 1
  scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: nginx-deployment
  targetCPUUtilizationPercentage: 90