apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app.kubernetes.io/name: nginx
spec:
  containers: 
    - name: web
      image: nginx:1.18
      ports:
       - name: web
         containerPort: 80
         protocol: TCP
  initContainers:
      - name: my-init-containers
        image: busybox
        command: ["/bin/sh"]
        args: ["-c", "echo 'Hello From initContainers' "]