apiVersion: v1
kind: PersistentVolume
metadata:
 name: app-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath: 
    path: "/home/app-pv"   #Nodes
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: app-pvc
 namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: app-pv